language: python
python:
- '3.6'
git:
  depth: 3
before_install:
- openssl aes-256-cbc -K $encrypted_c972c220410f_key -iv $encrypted_c972c220410f_iv
  -in deploy-key.enc -out deploy-key -d
- chmod 600 deploy-key
- eval $(ssh-agent -s)
- ssh-add deploy-key
- git config --global user.name "Kai.Zhou"
- git config --global user.email "zhoukaisspu@163.com"
install:
- pip install mkdocs
- mkdocs --version
- pip install mkdocs-material
script:
- cd ..
- git clone git@github.com:zhoukaisspu/zhoukaisspu.github.io.git
- cd zhoukai.sspu.git
- echo "hello" > readme.md
- git add .
- git commit -m "test commit"
- git push