# Set title for project documentation
site_name: Knowledge Sharing

# Set the name of author. This will add a meta data tag to the generated HTML header
site_author: Kai.Zhou
repo_url: https://github.com/zhoukaisspu/ks_blog
copyright: 'Copyright &copy; 2019 - 2019 Kai.Zhou'
theme:
  language: 'zh'
  name: 'material'
  feature:
    tabs: true
  logo:
    icon: 'cloud'
markdown_extensions:
  - admonition
  - codehilite
nav:
  - 'Home': index.md
  - 'javaScript':
    - '对象设计': JS/ObjectOriented.md
  - 'C++':
    - '核心特性':
      - '构造函数简介': C++/coreFeature/specialMemberFunction/constructor.md
      - '默认构造函数': C++/coreFeature/specialMemberFunction/default_constructor.md
      - '拷贝构造函数': C++/coreFeature/specialMemberFunction/copy_constructor.md
      - '移动构造函数': C++/coreFeature/specialMemberFunction/move_constructor.md
