# Set title for project documentation
site_name: Knowledge Sharing

# Set the name of author. This will add a meta data tag to the generated HTML header
site_author: Kai.Zhou
repo_url: https://github.com/zhoukaisspu/ks_blog
copyright: 'Copyright &copy; 2019 - 2019 Kai.Zhou'
theme:
  language: 'zh'
  name: 'material'
  feature:
    tabs: true
  logo:
    icon: 'cloud'
markdown_extensions:
  - admonition
  - codehilite
nav:
  - 'Home': 
    - 'Home': index.md
    - '网站部署': shell/CI/deployGithubIO.md
  - 'javaScript':
    - '对象设计': JS/ObjectOriented.md
  - 'C++':
    - '核心特性':
      - '构造函数': C++/coreFeature/specialMemberFunction/constructor.md
      - '委托构造': C++/coreFeature/specialMemberFunction/delegating_constructor.md
    - 'C++对象模型':
      - '局部静态对象': C++/objectModel/scoped_static.md
    - 'C++标准库':
      - 'std::thread': C++/standardLibrary/multiThread/thread.md
      - 'std::thread::native_handle': C++/standardLibrary/multiThread/thread_nativeHandle.md
    - 'C++技术总结':
      - '单例模式': C++/others/singleTon_mutex_call_once.md
      - '单例模式_2': C++/others/singleTon_atomic_static_member.md
  - 'python':
    - '进入python世界': python/home.md
    - '定义函数': python/function_py.md
    - '函数参数': python/functionParameter_py.md
  - 'swift':
    - 'Home: xcode的继续集成': swift/build.md
    - '1.1: 数据类型及变量': swift/basic.md
    - '1.2: 函数定义': swift/function.md
    - '2.1: 类基本': swift/class_basic.md
    - '2.2: 类属性': swift/class_property.md
    - '2.3: 类方法': swift/class_method.md
    - '2.4: 类subscript': swift/class_subscript.md
    - '2.5: 类型转换': swift/type_casting.md
  - 'linux':
    - 'linux':
      - 'Linux指令': shell/linux/command.md
      - 'Linux工具': shell/linux/tools.md
      - 'ext2文件系统': shell/linux/filesystem.md
      - '硬/符号链接': shell/linux/hard_softlink.md
      - 'FHS': shell/linux/fhs.md
    - 'shell Script':
      - 'shell script简介': shell/shellScript/home.md
      - '变量': shell/shellScript/variable.md
      - '条件判断': shell/shellScript/test.md
      - 'shell替换': shell/shellScript/substitution.md
      - '文件测试': shell/shellScript/file_operator.md
      - '函数定义': shell/shellScript/shell_function.md
      - '重定向': shell/shellScript/redirection.md
      - '调试': shell/shellScript/debug.md
